language: rust
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - cmake

rust:
  - nightly
  - stable
notifications:
  email:
    - s.pepyakin@gmail.com
before_script:
  - rustc --version
  - cargo --version
env:
  - CC=clang CXX=clang++
  - CC=gcc-7 CXX=g++-7
script:
  - cargo build --all --verbose
  # Run tests with --test-threads=1 as it looks like the linker runs out of memory
  # when linking doctests in parallel.
  - cargo test --all --verbose -- --test-threads=1
  - cargo test --manifest-path=binaryen-sys/Cargo.toml
